# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 「經濟時事與多媒體出版」迷你課程
email: mtlin@gm.ntpu.edu.tw
description: > # this means to ignore newlines until "baseurl:"
  國立臺北大學經濟學系「經濟時事與多媒體出版」迷你課程。



baseurl: "/minicourses" # the subpath of your site, e.g. /blog
url: "http://ntpuecon.github.io" # the base hostname & protocol for your site

#sidebar
default-image: webjeda-logo-big.jpg # If there is no featured image in a post then this image will be showed. Also on all pages this image will be showed. Use a 500x250 image.

#footer
built-by: E.Major Taiwan
copyright:
   name: E.Major Taiwan
   link: 'https://www.facebook.com/Emajortaiwanforu/'

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 6
paginate_path: /page:num/

# Tracker
analytics: UA-104915016-2

# Comments
disqus-shortname: webjeda-demo

#social
facebook: https://www.facebook.com/groups/ntpuecon.mpei/
github: http://github.com/webjeda

#facebook like box
fb-app-id: 516437792025417
fb-page-url: https://www.facebook.com/groups/ntpuecon.mpei/
fb-page-title: 經濟時事與多媒體出版

# Sass style
sass:
  style: compressed

# Ruby Gems
gems: [jekyll-paginate, jekyll-seo-tag, jekyll-paginate]

exclude: [minicourses]

# 讓post檔名為未來日期時，也可以立刻發佈出去
future: true
